package awesomegic.bank.operation;

/**
 * Represents the result of an operation.
 */
public class OperationResult {
    public final String feedback;
    public final boolean exit;

    /**
     * Constructs a new OperationResult with the specified feedback message.
     * The exit flag is set to false by default.
     *
     * @param feedback The feedback message generated by the operation.
     */
    OperationResult(String feedback) {
        this.feedback = feedback;
        this.exit = false;
    }

    /**
     * Constructs a new OperationResult with the specified feedback message and exit flag.
     *
     * @param feedback The feedback message generated by the operation.
     * @param exit {@code true} if the application should exit after processing the operation, {@code false} otherwise.
     */
    OperationResult(String feedback, boolean exit) {
        this.feedback = feedback;
        this.exit = exit;
    }
}
