/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package awesomegic.bank;

public class BankSystem {
    public String getGreeting() {
        return "Welcome to AwesomeGIC Bank";
    }

    public static void main(String[] args) {
        System.out.println(new BankSystem().getGreeting());
    }
}
