/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package awesomegic.bank;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class BankSystemTest {
    @Test void appHasAGreeting() {
        BankSystem classUnderTest = new BankSystem();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
