/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package awesomegic.bankingsystem;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class BankingSystemTest {
    @Test void appHasAGreeting() {
        BankingSystem classUnderTest = new BankingSystem();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
