/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package awesomegic.bankingsystem;

public class BankingSystem {
    public String getGreeting() {
        return "Welcome to AwesomeGIC Bank";
    }

    public static void main(String[] args) {
        System.out.println(new BankingSystem().getGreeting());
    }
}
